//Building a Food Delivery app from Scratch!!

//Importing React and ReactDOM
import React from "react";
import ReactDOM from "react-dom/client";
import imgLogo from "./images/foodDeliveryLogo.jpeg";

/**
 * Building the components
    Header- Logo,
    search bar,
     user Icon, 
     Nav items
* Body- 
    Restaurant container, 
    Restaurant cards
         -img
         -name
         -rating
         -cuisine
         -delivery time
     search bar
* Footer
        -copyright
        -contact us
        -links
**/

//Fucntional component for Header part of our app which contains Logo, Nav items etc
const Header = () => {
  return (
    <div className="header">
      <div className="Logo-container">
        <img className="Logo" src={imgLogo} />
      </div>
      <div className="nav-items">
        <ul>
          <li>Home</li>
          <li>About Us</li>
          <li>Contact Us</li>
          <li>Cart</li>
        </ul>
      </div>
    </div>
  );
};

const resObj = [
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "131870",
      name: "4M Biryani House",
      uuid: "3b8256f4-4e99-4cdf-8b9e-9dbd267af08a",
      city: "3",
      area: "Musheerabad",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "o685uklvqias8ez1qgxz",
      cuisines: ["Biryani", "Tandoor", "Chinese", "North Indian"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 42,
      minDeliveryTime: 42,
      maxDeliveryTime: 42,
      slaString: "42 MINS",
      lastMileTravel: 9.100000381469727,
      slugs: {
        restaurant: "4m-biryani-house-musheerabad-nallakunta-vidyanagar",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "Opposite Humera Hotel, Badi Masjid, Bholakpur, Musheerabad, Hyderabad",
      locality: "",
      parentId: 19646,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 11400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 11400,
        message: "",
        title: "Delivery Charge",
        amount: "11400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "9.1 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "ABOVE ₹700",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "131870",
        deliveryTime: 42,
        minDeliveryTime: 42,
        maxDeliveryTime: 42,
        lastMileTravel: 9.100000381469727,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.1",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "655635",
      name: "Vijju ki bandi",
      uuid: "05805dcd-80e7-4470-9355-104b00e039dd",
      city: "3",
      area: "Begumpet",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "b864a70c509ac70c3107deda2aebba85",
      cuisines: ["South Indian", "Chaat", "Fast Food"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 57,
      minDeliveryTime: 57,
      maxDeliveryTime: 57,
      slaString: "57 MINS",
      lastMileTravel: 6.5,
      slugs: {
        restaurant: "vijju-ki-bandi-begumpet-begumpet-2",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "CFRP+FV, Sappu Bagh Apaprtment, Jogani, Ramgopalpet, Hyderabad, Telangana 500003, India",
      locality: "Sappu Bagh Apaprtment",
      parentId: 258884,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 7400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 7400,
        message: "",
        title: "Delivery Charge",
        amount: "7400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "6.5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹100 OFF",
        subHeader: "ABOVE ₹599",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "655635",
        deliveryTime: 57,
        minDeliveryTime: 57,
        maxDeliveryTime: 57,
        lastMileTravel: 6.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.5",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "107824",
      name: "Asoka Restaurant",
      uuid: "fe227314-d454-4e5f-902c-6ec1e7955d4d",
      city: "3",
      area: "Shivaji Nagar",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "z54taxjog2tw6kg31pfl",
      cuisines: [
        "North Indian",
        "Chinese",
        "Hyderabadi",
        "Fast Food",
        "Seafood",
        "Tandoor",
        "Snacks",
      ],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 29,
      minDeliveryTime: 29,
      maxDeliveryTime: 29,
      slaString: "29 MINS",
      lastMileTravel: 7.5,
      slugs: {
        restaurant: "asoka-restaurant-secunderabad-somajiguda-khairtabad",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "9-1-14, Opposite secunderabad railway station entrance gate, Secunderabad",
      locality: "Regimental Bazar Main Rd",
      parentId: 19704,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 8400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 8400,
        message: "",
        title: "Delivery Charge",
        amount: "8400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "7.5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "10% OFF",
        subHeader: "ABOVE ₹600",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "107824",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        lastMileTravel: 7.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.8",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "20349",
      name: "Makers of Milkshakes",
      uuid: "46ba9c82-0ed7-4fb5-b713-323740c50811",
      city: "3",
      area: "Ramgopalpet",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "xnukkfyvf93vvhptms10",
      cuisines: ["Beverages", "Desserts", "Ice Cream"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 29,
      minDeliveryTime: 29,
      maxDeliveryTime: 29,
      slaString: "29 MINS",
      lastMileTravel: 6.599999904632568,
      slugs: {
        restaurant: "makers-of-milkshakes-begumpet-begumpet",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "Ashirwad Building, 1-8-160/11, Pendercast Road, Beside State Bank of India, Opp Federal Bank, Sindhi Colony",
      locality: "Beggum Nayyar road",
      parentId: 5632,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 7400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 7400,
        message: "",
        title: "Delivery Charge",
        amount: "7400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "6.5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹250 OFF",
        subHeader: "ABOVE ₹999",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "20349",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        lastMileTravel: 6.599999904632568,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.2",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "713034",
      name: "Shrimmers",
      uuid: "4e44bb03-74bb-4eb8-a94d-29cb3ec493bd",
      city: "3",
      area: "Padmarao nagar",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "cedfe674d5e12cd64ea8a75b482bc7ce",
      cuisines: ["Burgers", "Fast Food", "Snacks"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 42,
      minDeliveryTime: 42,
      maxDeliveryTime: 42,
      slaString: "42 MINS",
      lastMileTravel: 8.899999618530273,
      slugs: {
        restaurant: "shrimmers-nallakunta-&-vidyanagar-nallakunta-&-vidyanagar",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "D. NO. 11-1-667/2, /A, CHILAKALGUDA, CHINTA BAI, SECUNDERABAD, HYDERABAD, Secunderabad Circle No.29 , Hyderabad, Telangana-500061",
      locality: "Chilakalguda",
      parentId: 425877,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 9900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 9900,
        message: "",
        title: "Delivery Charge",
        amount: "9900",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "8.8 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "ABOVE ₹1000",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "713034",
        deliveryTime: 42,
        minDeliveryTime: 42,
        maxDeliveryTime: 42,
        lastMileTravel: 8.899999618530273,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.4",
      totalRatings: 100,
      new: true,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "424831",
      name: "KTM Kitchen",
      uuid: "1ade5db7-96c5-4ba8-8be7-a51c929e4abe",
      city: "3",
      area: "North Zone",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "mtegxluqad1aoqnkb1vb",
      cuisines: ["Chinese"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 55,
      minDeliveryTime: 55,
      maxDeliveryTime: 55,
      slaString: "55 MINS",
      lastMileTravel: 2.799999952316284,
      slugs: {
        restaurant: "ktm-kitchen-alwal-alwal",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        " 1-12-36, Golnaka, Alwal, Secunderabad,  Telangana 500010 , Alwal Circle No.27 , ",
      locality: "Alwal",
      parentId: 236441,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3100,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3100,
        message: "",
        title: "Delivery Charge",
        amount: "3100",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "2.7 kms",
      hasSurge: false,
      sla: {
        restaurantId: "424831",
        deliveryTime: 55,
        minDeliveryTime: 55,
        maxDeliveryTime: 55,
        lastMileTravel: 2.799999952316284,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.2",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "662703",
      name: "Peppy Chicken",
      uuid: "8900d6c6-3e13-4bcf-9da4-e5f0c7c80016",
      city: "3",
      area: "Ameerpet",
      totalRatingsString: "20+ ratings",
      cloudinaryImageId: "2228563b280a9ca1f4bc1d9eca217431",
      cuisines: ["Fast Food", "Burgers", "Snacks"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 51,
      minDeliveryTime: 51,
      maxDeliveryTime: 51,
      slaString: "51 MINS",
      lastMileTravel: 9.5,
      slugs: {
        restaurant: "peppy-chicken-ameerpet-ameerpet",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "214b, Balkampet Internal Rd, Scientific Colony, BK Guda, Sanjeeva Reddy Nagar, Hyderabad, Telangana 500038, India",
      locality: "Balkampet Internal Rd",
      parentId: 378906,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "distance",
            fee: 11400,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 11400,
        message: "",
        title: "Delivery Charge",
        amount: "11400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "9.5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "25% OFF",
        subHeader: "ABOVE ₹159",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "662703",
        deliveryTime: 51,
        minDeliveryTime: 51,
        maxDeliveryTime: 51,
        lastMileTravel: 9.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.6",
      totalRatings: 20,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "16571",
      name: "Subway",
      uuid: "8a7457c7-34e0-41ac-b86d-428d57d7f464",
      city: "3",
      area: "SP Road",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "1ace5fa65eff3e1223feb696c956b38b",
      cuisines: ["Salads", "Snacks", "Desserts", "Beverages"],
      tags: [],
      costForTwo: 35000,
      costForTwoString: "₹350 FOR TWO",
      deliveryTime: 58,
      minDeliveryTime: 58,
      maxDeliveryTime: 58,
      slaString: "58 MINS",
      lastMileTravel: 7.900000095367432,
      slugs: {
        restaurant: "subway-s-p-road-begumpet",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "Door No. 1-8-303/34/GB4, May Fair Building, S P Road, Begumpet, Secunderabad, Telangana 500003",
      locality: "SP Road",
      parentId: 2,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 8400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 8400,
        message: "",
        title: "Delivery Charge",
        amount: "8400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "7.9 kms",
      hasSurge: false,
      sla: {
        restaurantId: "16571",
        deliveryTime: 58,
        minDeliveryTime: 58,
        maxDeliveryTime: 58,
        lastMileTravel: 7.900000095367432,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.0",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "668148",
      name: "Make My Combo",
      uuid: "1ddbad9d-f471-4dc6-9252-3163fb3f7639",
      city: "3",
      area: "Ameerpet",
      totalRatingsString: "20+ ratings",
      cloudinaryImageId: "5c0a9238559d41786a81825e632e28f6",
      cuisines: ["Burgers", "Pizzas", "Snacks"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 55,
      minDeliveryTime: 55,
      maxDeliveryTime: 55,
      slaString: "55 MINS",
      lastMileTravel: 9.899999618530273,
      slugs: {
        restaurant: "make-my-combo-ameerpet-ameerpet",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "HOUSE NO.214/B, BALKAMPET ,S R NAGAR ,AMEERPET ,Hyderabad,Telangana,500038",
      locality: "S R Nagar",
      parentId: 340371,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 11400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 11400,
        message: "",
        title: "Delivery Charge",
        amount: "11400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "9.8 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "25% OFF",
        subHeader: "ABOVE ₹159",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "668148",
        deliveryTime: 55,
        minDeliveryTime: 55,
        maxDeliveryTime: 55,
        lastMileTravel: 9.899999618530273,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "2.9",
      totalRatings: 20,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "587392",
      name: "Spice Of Arabia",
      uuid: "f90c0deb-ac17-4c75-bf9c-5ac0b0e79b15",
      city: "3",
      area: "Balkampet",
      totalRatingsString: "50+ ratings",
      cloudinaryImageId: "nllpeckyij3gnscnz0x0",
      cuisines: ["Snacks"],
      tags: [],
      costForTwo: 19900,
      costForTwoString: "₹199 FOR TWO",
      deliveryTime: 49,
      minDeliveryTime: 49,
      maxDeliveryTime: 49,
      slaString: "49 MINS",
      lastMileTravel: 9.100000381469727,
      slugs: {
        restaurant: "spice-of-arabia-kondapur-kondapur",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        " H No 7-1-246/2/B/8, Renuka Nagar, Balkampet , Khairatabad Circle No.17 ,Hyderabad, Telangana - 500038 ",
      locality: "Renuka Nagar",
      parentId: 277788,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 11400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 11400,
        message: "",
        title: "Delivery Charge",
        amount: "11400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "9.1 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "587392",
        deliveryTime: 49,
        minDeliveryTime: 49,
        maxDeliveryTime: 49,
        lastMileTravel: 9.100000381469727,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.4",
      totalRatings: 50,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "385744",
      name: "Laxmi Chat Bandar",
      uuid: "0d2a6e83-d012-4ab2-b0b6-c78c9a69c15c",
      city: "3",
      area: "Ameerpet",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "tbclhvute8yequiqziow",
      cuisines: ["Chaat", "Snacks"],
      tags: [],
      costForTwo: 9900,
      costForTwoString: "₹99 FOR TWO",
      deliveryTime: 39,
      minDeliveryTime: 39,
      maxDeliveryTime: 39,
      slaString: "39 MINS",
      lastMileTravel: 8.199999809265137,
      slugs: {
        restaurant: "laxmi-chat-bhandar-ameerpet-ameerpet",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "4-68, Nethaji Nagar, Fatehnagar, Begumpet, Hyderabad, Telangana 500018, India",
      locality: "Fatehnagar",
      parentId: 123891,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 9900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 9900,
        message: "",
        title: "Delivery Charge",
        amount: "9900",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "8.1 kms",
      hasSurge: false,
      sla: {
        restaurantId: "385744",
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        lastMileTravel: 8.199999809265137,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.1",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "713033",
      name: "Peppanizze",
      uuid: "29fb468f-ba8f-4ef2-8bc0-19ae9c34f5f1",
      city: "3",
      area: "Padmarao nagar",
      totalRatingsString: "50+ ratings",
      cloudinaryImageId: "d1f427e88dde5cc6fb1a6eae2f56a700",
      cuisines: ["Pizzas", "Snacks", "Beverages"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 46,
      minDeliveryTime: 46,
      maxDeliveryTime: 46,
      slaString: "46 MINS",
      lastMileTravel: 8.899999618530273,
      slugs: {
        restaurant:
          "peppanizze-nallakunta-&-vidyanagar-nallakunta-&-vidyanagar",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "D. NO. 11-1-667/2, /A, CHILAKALGUDA, CHINTA BAI, SECUNDERABAD, HYDERABAD, Secunderabad Circle No.29 , Hyderabad, Telangana-500061",
      locality: "Chilakalguda",
      parentId: 425704,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 9900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 9900,
        message: "",
        title: "Delivery Charge",
        amount: "9900",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "8.8 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "30% OFF",
        subHeader: "UPTO ₹75",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "713033",
        deliveryTime: 46,
        minDeliveryTime: 46,
        maxDeliveryTime: 46,
        lastMileTravel: 8.899999618530273,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.7",
      totalRatings: 50,
      new: true,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "481966",
      name: "Olio - The Wood Fired Pizzeria",
      uuid: "4b301a55-fb13-4e38-9d45-e6e25df85770",
      city: "3",
      area: "Patny Nagar",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "voqn5szg4lglqfsdhcdk",
      cuisines: ["Pizzas", "Italian"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 66,
      minDeliveryTime: 66,
      maxDeliveryTime: 66,
      slaString: "66 MINS",
      lastMileTravel: 7,
      slugs: {
        restaurant: "the-wood-fired-pizzeria-sardar-patel-road-secunderabad",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "Scb Door No.3-14-011,Ground Floor,Patny Square,Patny Nagar,Sardar Patel Road,Sy No.47,Rasoolpura,Secunderabad, Secunderabad Circle No.29 , Hyderabad, North Zone, Telangana, 500003",
      locality: "Rasoolpura",
      parentId: 11633,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 8400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 8400,
        message: "",
        title: "Delivery Charge",
        amount: "8400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 1,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "7 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹249",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "481966",
        deliveryTime: 66,
        minDeliveryTime: 66,
        maxDeliveryTime: 66,
        lastMileTravel: 7,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "IT_IS_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.0",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "699008",
      name: "Fryko",
      uuid: "5c93dbb3-0675-4275-80ff-fde66ee1f111",
      city: "3",
      area: "Ameerpet",
      totalRatingsString: "20+ ratings",
      cloudinaryImageId: "d8acc3f7326b989784a5673070cbe1fd",
      cuisines: ["Snacks", "Beverages"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 43,
      minDeliveryTime: 43,
      maxDeliveryTime: 43,
      slaString: "43 MINS",
      lastMileTravel: 9.100000381469727,
      slugs: {
        restaurant: "fryko-ameerpet-ameerpet",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "7-1-246/2/B/8, Suprabath Nagar Colony, Balkampet, Hyderabad, Telangana 500016, India",
      locality: "Suprabath Nagar Colony",
      parentId: 282362,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 11400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 11400,
        message: "",
        title: "Delivery Charge",
        amount: "11400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "9.1 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "699008",
        deliveryTime: 43,
        minDeliveryTime: 43,
        maxDeliveryTime: 43,
        lastMileTravel: 9.100000381469727,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.4",
      totalRatings: 20,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "534849",
      name: "Mealicious",
      uuid: "32fdc45d-0190-4356-bea2-195154cf4646",
      city: "3",
      area: "Balkampet ",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "kywpfrr4v7i2exfky0pj",
      cuisines: ["Biryani"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 49,
      minDeliveryTime: 49,
      maxDeliveryTime: 49,
      slaString: "49 MINS",
      lastMileTravel: 9.100000381469727,
      slugs: {
        restaurant: "mealicious-jeedimetla-&-chintal-jeedimetla-&-chintal",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        " H No 7-1-246/2/B/8, Renuka Nagar, Balkampet , Khairatabad Circle No.17 ,Hyderabad, Telangana - 500038 ",
      locality: "Renuka Nagar",
      parentId: 134398,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 11400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 11400,
        message: "",
        title: "Delivery Charge",
        amount: "11400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "9.1 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "534849",
        deliveryTime: 49,
        minDeliveryTime: 49,
        maxDeliveryTime: 49,
        lastMileTravel: 9.100000381469727,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
];

//Fucntional component for the Restaurant Card which is part of the body
//Res-card dets and res-img are contained in the res-card.
//The source for image is the from the cloudinary site, with the ImageID changing for each image.
//To reuse the Restaurant car component with multiple values we use props, destructure it and use the properties of it with {}'s
const RestaurantCard = (props) => {
  const { resData } = props;
  const { cloudinaryImageId, name, cuisines, avgRating, deliveryTime } =
    resData?.data;

  return (
    <div className="res-card">
      <div className="res-card-dets">
        <img
          className="res-img"
          src={
            "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/" +
            cloudinaryImageId
          }
        ></img>
        <h3>{name}</h3>
        <p>{cuisines.join(", ")} </p>
        <p>{avgRating} stars</p>
        <p>{deliveryTime} minutes</p>
      </div>
    </div>
  );
};

//Fucntional component for Body part of our app which contains Restaurant container, Restaurant cards and seach bar
//The res-container is the whole place where all the cards will be placed. The map function is used over the resObj which will iterate for all values of the list where "restaurant "
//is the function arguement which returns the Restuarant card component with particular resData and key.
const Body = () => {
  return (
    <div className="Body">
      <div className="res-container">
        {resObj.map((restaurant) => (
          <RestaurantCard key={restaurant.data.id} resData={restaurant} />
        ))}
      </div>
      <div className="SearchBar"> Search </div>
    </div>
  );
};

//Functional component which returns the whole app layout with the header, body and footer components
const App = () => {
  return (
    <div className="app">
      <Header />
      <Body />
    </div>
  );
};

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<App />);
